# Generated by Django 3.0.7 on 2020-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('directory', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
